import { singleton } from "tsyringe";
import { z } from "zod";

@singleton()
export class ReportSchema {
  private static instance: ReportSchema;
  private reportBase = z.object({
    id: z.string(),
    title: z.string(),
    description: z.string().optional(),
    type: z.string(),
    generatedBy: z.string(),
    generatedAt: z.date(),
    filePath: z.string(),
    parameters: z.string(),
  });

  public getBaseReport() {
    return this.reportBase;
  }

  public createReport() {
    return z.object({
      title: z
        .string({ message: "Title is required!" })
        .min(1, { message: "Title is required!" }),
      description: z.string().optional(),
      type: z
        .string({ message: "Report type is required!" })
        .min(1, { message: "Report type is required!" }),
      generatedBy: z
        .string({ message: "Generated by user ID is required!" })
        .min(1, { message: "Generated by user ID is required!" }),
      generatedAt: z.date({ message: "Generation date is required!" }),
      filePath: z
        .string({ message: "File path is required!" })
        .min(1, { message: "File path is required!" }),
      parameters: z
        .string({ message: "Parameters are required!" })
        .min(1, { message: "Parameters are required!" }),
    });
  }

  public updateReportDTO() {
    return z
      .object({
        title: z
          .string({ message: "Title is required!" })
          .min(1, { message: "Title is required!" }),
        description: z.string().optional(),
        type: z
          .string({ message: "Report type is required!" })
          .min(1, { message: "Report type is required!" }),
        filePath: z
          .string({ message: "File path is required!" })
          .min(1, { message: "File path is required!" }),
        parameters: z
          .string({ message: "Parameters are required!" })
          .min(1, { message: "Parameters are required!" }),
      })
      .partial();
  }

  public static getInstance() {
    if (!ReportSchema.instance) {
      ReportSchema.instance = new ReportSchema();
    }
    return ReportSchema.instance;
  }
}
